# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1b34eba91d1e574ad6407636703602ba"
name = "boa-home-task-DB"
application_url = "https://herein-characterized-eu-sunset.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-52.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://herein-characterized-eu-sunset.trycloudflare.com/auth/callback",
  "https://herein-characterized-eu-sunset.trycloudflare.com/auth/shopify/callback",
  "https://herein-characterized-eu-sunset.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
